### ISSUE TITLE
The public data model cannot be put in "internal" package.

### ISSUE THREAD

**Issue by lrita** [arriqaaq/chord#1]
Since go1.5 support ["internal package"](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit) feature, the public data model cannot be put in "internal" package.

**Comment by arriqaaq** [comment]
Hey @lrita , thanks for the read. From the paper doesn't internal package satisfy the following >
"Code in /a/b/c/internal/d/e/f can be imported only by code in the directory tree rooted at /a/b/c. It cannot be imported by code in /a/b/g."  Do lemme a know a lil bit in detail, would appreciate it

**Comment by lrita** [comment]
If someone want to use this chord algorithm implementation in his repo, and copy the example code to somewhere, it cannot be compiled. The compiler will blame `use of internal package github.com/arriqaaq/chord/internal not allowed`. Because of the package `github.com/arriqaaq/chord/internal` is a private package of `github.com/arriqaaq/chord`. Only the subpackages of `github.com/arriqaaq/chord` can import it.

**Comment by arriqaaq** [comment]
Thank you Irita, I have fixed this. Sorry for the late reply
